# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

FROM node:22 AS base

# Enable corepack
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable

# Setup PNPM
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PNPM_HOME/bin:$PATH"
RUN mkdir -p /home/codespace/.pnpm-store /pnpm \
    && chown -R 1000:1000 /home/codespace/.pnpm-store /pnpm

#Install Bun
COPY --from=oven/bun:1.3.11-alpine /usr/local/bin/bun /usr/local/bin/bun

# Install dependencies only when needed
FROM base AS deps

WORKDIR ${FOLDER}

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED=1

USER 1000:1000

# Apply PNPM settings to be consistent with devcontainer
ENV CI=true
ENV PNPM_CONFIG_NODE_LINKER=hoisted
ENV PNPM_CONFIG_MINIMUM_RELEASE_AGE=0
ENV PNPM_CONFIG_STRICT_DEP_BUILDS=false
ENV PNPM_CONFIG_CONFIRM_MODULES_PURGE=false
RUN pnpm config set store-dir /home/codespace/.pnpm-store --global

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
