apiVersion: apps/v1
{{- if eq .Values.stage "development"}}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  {{- if eq .Values.stage "development"}}
  serviceName: app
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: diploi-pull-secret
      # TODO: This should only run once?
      initContainers:
        - name: install-dependencies
          image: ghcr.io/diploi/component-nextjs:main
          imagePullPolicy: Always
          command: ['npm', 'install']
          workingDir: /app/nextjs
          env:
          - name: NODE_ENV
            value: development
          securityContext:
            runAsUser: 0  # Ensure it runs as root
          volumeMounts:
            - name: app-mount
              mountPath: /app
      containers:
        - name: app
          image: ghcr.io/diploi/component-nextjs:main
          imagePullPolicy: Always
          workingDir: /app/nextjs
          ports:
            - containerPort: 3000
          {{- if eq .Values.stage "development"}}
          resources:
            requests:
              memory: 1500Mi
            limits:
              memory: 2000Mi
          {{- else }}
          resources:
            requests:
              memory: 500Mi
            limits:
              memory: 1000Mi
          {{- end }}
          env:
            {{ range $key, $val := .Values.parameterGroupsEnabled }}
            {{ if $val }}
            - name: parameter_group_{{ $key }}_enabled
              value: "1"
            {{ end }}
            {{ end }}
            {{- range .Values.env }}
            {{- if contains "app" .contexts }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            {{- range .Values.parameterGroups }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            - name: APP_PUBLIC_URL
              value: {{ .Values.hosts.app }}
            - name: STAGE
              value: {{ .Values.stage }}
          volumeMounts:
            {{- if hasKey .Values.storage "app" }}
            - name: app-mount
              mountPath: /app
            #- name: root-mount
            #  mountPath: /root
            {{- end }}
      volumes:
        {{- if hasKey .Values.storage "app" }}
        - name: app-mount
          hostPath:
            path: {{ .Values.storage.app.hostPath }}
        #- name: root-mount
        #  hostPath:
        #    path: {{ .Values.storage.approot.hostPath }}
        {{- end }}
